package com.acme.rfqproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Product implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String id;
	private java.lang.String name;
	private java.lang.String desciption;
	private java.lang.String price;

	private java.lang.String storeLocation;

	public Product() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getDesciption() {
		return this.desciption;
	}

	public void setDesciption(java.lang.String desciption) {
		this.desciption = desciption;
	}

	public java.lang.String getPrice() {
		return this.price;
	}

	public void setPrice(java.lang.String price) {
		this.price = price;
	}

	public java.lang.String getStoreLocation() {
		return this.storeLocation;
	}

	public void setStoreLocation(java.lang.String storeLocation) {
		this.storeLocation = storeLocation;
	}

	public Product(java.lang.String id, java.lang.String name,
			java.lang.String desciption, java.lang.String price,
			java.lang.String storeLocation) {
		this.id = id;
		this.name = name;
		this.desciption = desciption;
		this.price = price;
		this.storeLocation = storeLocation;
	}

}